# This is a basic workflow to help you get started with Actions

name: Run unit tests

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master, dev ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Store secrets
        run: |
          echo ${{ secrets.MONGO_URI }}
          echo "MONGO_URI=${{ secrets.MONGO_URI }}"
      - name: Run tests with pytest
        run: pytest 

